<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SFR-6086" name="CIMS Automation Report" tests="3" failures="3" timestamp="24 May 2016 15:46:55 GMT" time="205.649" errors="0">
  <testcase name="CIMSMain" time="147.763" classname="CIMS.CIMS_MainProject">
    <failure type="java.lang.Throwable" message="Multiple failures (5):

Failure 1 of 5:
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(Unknown Source)
	at java.io.File.getCanonicalPath(Unknown Source)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1079)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at util.UtilFunction.takeScreenShot(UtilFunction.java:945)
	at CIMS.Modules.CIMS_Login.TakeScreenshot(CIMS_Login.java:284)
	at CIMS.Modules.CIMS_Login.Welcome_Page(CIMS_Login.java:140)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 2 of 5:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 3 of 5:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_MainProject.ScenarioAndTotalcounter(CIMS_MainProject.java:7030)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:709)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 4 of 5:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_MainProject.ScenarioAndTotalcounter(CIMS_MainProject.java:7030)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:709)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 5 of 5:
java.lang.Throwable: Error occoured while fetching the data from excel sheet.">
      <![CDATA[java.lang.Throwable: Multiple failures (5):

Failure 1 of 5:
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(Unknown Source)
	at java.io.File.getCanonicalPath(Unknown Source)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1079)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at util.UtilFunction.takeScreenShot(UtilFunction.java:945)
	at CIMS.Modules.CIMS_Login.TakeScreenshot(CIMS_Login.java:284)
	at CIMS.Modules.CIMS_Login.Welcome_Page(CIMS_Login.java:140)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:329)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 2 of 5:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:437)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 3 of 5:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_MainProject.ScenarioAndTotalcounter(CIMS_MainProject.java:7030)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:709)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 4 of 5:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_MainProject.ScenarioAndTotalcounter(CIMS_MainProject.java:7030)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:709)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 5 of 5:
java.lang.Throwable: Error occoured while fetching the data from excel sheet.
	at util.UtilFunction.getCellData(UtilFunction.java:406)
	at CIMS.Modules.CIMS_USImmigration_Module.USImmigrationPage(CIMS_USImmigration_Module.java:73)
	at CIMS.CIMS_MainProject.CIMSMain(CIMS_MainProject.java:715)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 80 stack frames]]>
    </failure>
  </testcase> <!-- CIMSMain -->
  <testcase name="CIMS_Dashboard" time="16.199" classname="CIMS.CIMS_Dashboard">
    <failure type="java.lang.Throwable" message="Multiple failures (2):

Failure 1 of 2:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_Dashboard.numberOfCounters(CIMS_Dashboard.java:217)
	at CIMS.CIMS_Dashboard.CIMS_Dashboard(CIMS_Dashboard.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 2 of 2:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.">
      <![CDATA[java.lang.Throwable: Multiple failures (2):

Failure 1 of 2:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_Dashboard.numberOfCounters(CIMS_Dashboard.java:217)
	at CIMS.CIMS_Dashboard.CIMS_Dashboard(CIMS_Dashboard.java:82)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Failure 2 of 2:
java.lang.Throwable: Error occoured while getting the column number with data from excel sheet.
	at util.UtilFunction.getColumnWithCellData(UtilFunction.java:650)
	at CIMS.CIMS_Dashboard.numberOfCounters(CIMS_Dashboard.java:218)
	at CIMS.CIMS_Dashboard.CIMS_Dashboard(CIMS_Dashboard.java:82)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CIMS_Dashboard -->
  <testcase name="CIMSMain" time="27.099" classname="CIMS.CIMSEmail">
    <failure type="javax.mail.SendFailedException" message="Sending failed;
  nested exception is:
	class javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
  nested exception is:
	java.net.ConnectException: Connection timed out: connect">
      <![CDATA[javax.mail.SendFailedException: Sending failed;
  nested exception is:
	class javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
  nested exception is:
	java.net.ConnectException: Connection timed out: connect
	at javax.mail.Transport.send0(Transport.java:218)
	at javax.mail.Transport.send(Transport.java:80)
	at util.Email.postMail(Email.java:166)
	at util.Email.SendMailtoUser(Email.java:71)
	at CIMS.CIMSEmail.CIMSMain(CIMSEmail.java:51)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- CIMSMain -->
</testsuite> <!-- CIMS Automation Report -->
